dist: bionic
language: python
python:
  - "3.8"

install:
  - pip install -r requirements.txt

script:
  - python update-data.py 2852TH-level-stage-i-15_min-mASD data/
  - python update-data.py 2859TH-level-downstage-i-15_min-mASD data/
  - python update-data.py 2859TH-level-stage-i-15_min-mASD data/
  - python update-data.py 278744TP-rainfall-tipping_bucket_raingauge-t-15_min-mm data/
  - python plot-stages.py 2852TH-level-stage-i-15_min-mASD "Chesham"
  - python plot-stages.py 2859TH-level-stage-i-15_min-mASD "Rickmansworth"
  - python plot-stages-1-month.py 2852TH-level-stage-i-15_min-mASD "Chesham"
  - python plot-stages-1-month.py 2859TH-level-stage-i-15_min-mASD "Rickmansworth"
  - python plot-daily-rain.py
  - python plot-daily-rain-1-month.py

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: main
  on:
    branch: main
