dist: bionic
language: python
python:
  - "3.8"

install:
  - pip install -r requirements.txt

script:
  python plot-daily-rain.py

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main
