name: daily-chesswatch-update
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # You can test your matrix by printing the current Python version
      - name: Update data
        run: python update-data.py 2852TH-level-stage-i-15_min-mASD data/
