name: daily-chesswatch-update

on:
  schedule:
  - cron:  '58 14 * * *'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Update data
        run: |
          python update-data.py 2852TH-level-stage-i-15_min-mASD data/
          python update-data.py 2859TH-level-downstage-i-15_min-mASD data/
          python update-data.py 2859TH-level-stage-i-15_min-mASD data/
          python update-data.py 278744TP-rainfall-tipping_bucket_raingauge-t-15_min-mm data/

      - name: Generate plots
        run: |
          python plot-stages.py 2852TH-level-stage-i-15_min-mASD "Chesham"
          python plot-stages.py 2859TH-level-stage-i-15_min-mASD "Rickmansworth"
          python plot-stages-1-month.py 2852TH-level-stage-i-15_min-mASD "Chesham"
          python plot-stages-1-month.py 2859TH-level-stage-i-15_min-mASD "Rickmansworth"
          python plot-daily-rain.py
          python plot-daily-rain-1-month.py

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[AUTO] Daily update of data and plots'
