name: daily-chesswatch-update

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Update data
        run: python update-data.py 2852TH-level-stage-i-15_min-mASD data/

      - name: Generate plots
        run: python plot-stages.py 2852TH-level-stage-i-15_min-mASD "Chesham"

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: [AUTO] Daily update of data and plots
